### PR TITLE
Fixes and Optimization

### LINKED ISSUE #25: Poor performance on O3DS
Even at 400px with AA disabled I can't match the performance I get with a build from sm64-port/sm64-port at 800px + AA, that can otherwise run the game at full speed, except when a song starts playing, like when you pick up the wing cap.

### PR DESCRIPTION
**Pull request by Wyatt-James**
Optimization is improved significantly, some bugs have been fixed, and some polish has been added. Performance is now effectively perfect.

Full testing has been performed on old 3DS, and limited testing on old 2DS and new 3DS.

Known Issues:
- Regression: If 3D is enabled, the credits have a visual anomaly on the sides. This is because the full framebuffer is no longer cleared. The ideal fix is to adjust the screen windowing effect to account for this, but the screen could just be fully cleared instead. See gfx_citro3d.h.
- New Issue: There is a race condition related to the audio thread's and Thread5's use of load.c. It does not appear to matter at all during normal operation, but if the game is recompiled with a very low App CPU limit (I tested with 20%), the game will crash very quickly. I don't have the patience to fix this, as the game ran perfectly during a 120-star test playthrough of RC3 and RC6.
- Complicated: There is visible stuttering present in some areas on old 3DS. This appears to be due to the game jumping between vsync intervals, likely caused by judder on the audio thread. This could be improved with a dummy wait, always hitting the later interval. I believe this to be a bug with Citro3D's frame rate limiter and vsync.

Bug Fixes and Polishing:
- The touch screen now ignores button presses when they will have no effect (changing settings with 3D enabled)
- The screens now only clear when necessary. The top screen no longer clears the frame buffer twice each frame, and the bottom screen now only clears when it is updated.
- The touch screen is no longer rendered every frame; instead, it is only rendered when it is interacted with. This mitigates the visibility of the "PRESS START" visual bug, as it is now only seen if the screen is interacted with while that text is on-screen.
- The touch screen's debounce timer now accounts for different framerates better.
- The Home Menu is no longer extremely laggy on old 3DS when running with multi-core audio. The App CPU Time Limit is dynamically changed when the game is suspended/resumed.
- The game no longer continues running while the the lid is closed.
- Fixed some potential bugs caused by variables that should have been volatile, but were not.
- The EU version now runs at 25 fps instead of 30, matching the original game.

Optimizations:
- The audio thread now runs for much more time during the game frame. Originally, it ran for a rather short duration, but now, it runs for almost the entire frame during gameplay. When this is not feasible, such as during loading screens, the main thread waits for the audio thread to finish.
- The synthesizer and mixer now avoid some redundant data copying. Notably, sample data is no longer copied to the emualated RSPA, and the output PCM audio stream is now copied directly into the DSP buffer when possible (functionally always). See `Developer Notes/Enhanced RSPA.`
- The 3DS `mixer.c` has received some heavy optimizations. Notably, these include:
  - Less-accurate rounding is used to improve performance, with practically identical audio quality. This can be reverted with a build flag.
  - ARMv6 SIMD32 and Saturating Arithmetic instructions are used when possible to slightly improve performance. This is NOT the 3DS DSP. This can be disabled in `mixer.c` via use of a separate implementation file.
  - Some code has been altered to use ARMv6 conditional execution, reducing branching and improving performance.
  - Loop unrolling is now manually specified in cases where this improves performance.
  - Some code was rewritten to reduce resemblance to re-implemented SIMD code. This is mostly a performance wash, but readability was improved.
- The 3DS export to DSP has been optimized by switching from DSP_FlushDataCache to svcFlushProcessDataCache. Both were effectively instant when AppCPUTimeLimit is low, but DSP_FlushDataCache became very slow and juddery when set high. svcFlushProcessDataCache does not suffer from this issue.
- CPU vertex and triangle transform has been optimized slightly.

Developer Notes:
- Added a more generalized performance profiler, located in `src/pc/profiler_3ds.c` and its header. It can be globally enabled with an edit to the header file. It is intended to be used with a debugger to dump performance data via GDB printing statements. It is NOT thread-safe.
- LibCTRU type redefinition has been improved slightly.
- Mixer.c is now a stub class that #includes one of several .c implementation files, selected via a combination of build flags and compiler-provided flags. This greatly improves readability, as there are no longer mazes of IFDEFs around things like SSE4.3 and ARM Neon. Additionally, different implementations can easily be forced; see `README.md.`
- The Citro3D Rendering API now includes functions for managing screen clearing. See gfx_citro3d.h.
- A file full of color conversion macros has been added at `src/pc/gfx/color_conversion.h.` It is currently unused, as the changes that made use of it have been reverted.
- Multi-viewport support is now slightly more generalized.
- The Makefile now has additional build flags, noted in `README.md.`
- The Makefile now once again respects optimiaztion flags passed in from the command line.
- The Makefile now defaults to -O3 optimization.
- Synthesis.c received more documentation, and synthesis_process_notes received a large rewrite for the US version, vastly improving readability.
- Enhanced RSPA Emulation is an optional API available in supporting mixer.c implementations. It allows audio data from outside of the emulated RSPA to be utilized directly, without loading it into the RSPA first. This API is dynamically enabled by `mixer.h.` However, it is unfinished, as most functions did not receive altered versions due to time constraints.
- If audio is set to run on 3DS CPU0, it is now handled by Thread5 instead of a separate synchronous thread.
- Not all optimizations are available on the EU version, but most are.

Important note: audio performance is now effectively perfect, with several milliseconds to spare. The bottleneck is now solely the main thread. Vertex/triangle processing is the slowest step by far, and is the last barrier keeping o3DS from maintaining 60fps. In my benchmark, they total to ~21ms! Moving vertex processing to a vertex shader would be the best option.

Potential Future Optimizations:
- A custom DSP firmware could further improve performance, but this is unnecessary. This may reduce the judder.
- All uses of N64 DMA could be removed from the 3DS audio code, as the data is already present in RAM. This could possibly save a couple milliseconds per frame, and might eliminate race conditions. This would also allow truly asynchronous audio.

I have a set of audio thread profiler measurements and main thread profiler measurements, software to analyze them, and software to graph them. The data and software can be provided on request.

Fixes #25

### CODE REVIEW

**Comment by CreepercraftYT** [comment]
hi :)

**Comment by Dima353** [comment]
Can this be combined with the minimap version?

**Comment by Wyatt-James** [comment]
The minimap branch could receive these changes after this PR is merged if somebody wants to put in the work.

**Comment by Wyatt-James** [comment]
With these most recent changes, performance is effectively perfect. Audio now has multiple milliseconds of headroom in my most expensive benchmark. I will edit the PR description and log the edits in another comment.

**Comment by Wyatt-James** [comment]
Updates to the main comment:
- Updated testing information.
- Updated known issue 3: visible stuttering.
- Added information denoting DSP cache flush optimization.
- Removed developer note for disabling frameskip by default, as this is now the case.
- Added information denoting -O3 optimization being made default.
- Added note related to audio performance and feasibility of 60fps on o3DS.
- Removed some potential future optimizations that are now truly unnecessary.

**Comment by Wyatt-James** [comment]
It is worth noting that the Luma3DS version requirement may have changed with the usage of svcFlushProcessDataCache.

**Comment by Wyatt-James** [comment]
For unknown reasons, the game may crash if closing and opening the lid rapidly. This is new to this fork, as the base version does not enable 3DS sleep. I am completely unsure as to why this occurs; my best guess is that Citro3D could be stuck waiting for VBlank while the system is in sleep. It is NOT related to thread synchronization as it occurs even in single-threaded audio mode. In any event, it's rare enough to not matter much at all.

**Pull request merged**
